import './styles/base.css';
import './styles/home.css';
import './styles/villa.css';
import { VILLAS } from './data/villas.js';
import { icon } from './ui/icons.js';
import { initCursor } from './ui/fx.js';
import { reduced } from './ui/utils.js';
import { homePage } from './pages/home.js';
import { villaPage } from './pages/villa.js';

if (reduced()) document.documentElement.classList.add('reduce');

const shell = document.getElementById('shell');
const boot = document.getElementById('boot');
const bootBar = boot.querySelector('.boot__bar i');

shell.innerHTML = `
  <header class="header" id="header">
    <a class="brand" href="#/" aria-label="Solenne — home"><span class="brand__mark">${icon.mark}</span><b>SOLENNE</b></a>
    <nav class="nav" aria-label="Primary">
      <a href="#collection" data-go-id="collection">Residences</a>
      <a href="#experience" data-go-id="experience">Experience</a>
      <a href="#about" data-go-id="about">About</a>
    </nav>
    <div class="header__cta"><a class="btn btn--ghost" href="#private-viewing" data-go-id="private-viewing" data-magnetic>Private viewing</a></div>
    <button class="menu-btn" type="button" aria-label="Menu" aria-expanded="false" aria-controls="sheet"><i></i><i></i></button>
  </header>
  <div class="sheet" id="sheet" aria-label="Menu">
    <a href="#collection" data-go-id="collection">Residences</a>
    <a href="#experience" data-go-id="experience">Experience</a>
    <a href="#about" data-go-id="about">About</a>
    <a href="#private-viewing" data-go-id="private-viewing">Private viewing</a>
  </div>
  <div id="view"></div>
  <footer class="footer">
    <div class="wrap">
      <div class="footer__grid">
        <div><p class="footer__word">Solenne</p><p class="body">Private residences on the Mediterranean and Atlantic coast.</p></div>
        <div><h4>Residences</h4><ul>${VILLAS.slice(0, 4).map((v) => `<li><a href="#/villa/${v.slug}">${v.name}</a></li>`).join('')}</ul></div>
        <div><h4>&nbsp;</h4><ul>${VILLAS.slice(4).map((v) => `<li><a href="#/villa/${v.slug}">${v.name}</a></li>`).join('')}</ul></div>
        <div><h4>Offices</h4><ul><li>Marbella</li><li>Palma de Mallorca</li><li>Lisbon</li><li>Monaco</li><li>Dubai</li></ul></div>
      </div>
      <div class="footer__base"><span>© Solenne. A fictional brand created as a design and engineering demonstration.</span><span>All properties, names and prices are invented. Imagery is generated by the site’s own 3D engine.</span></div>
    </div>
  </footer>
  <div class="curtain" id="curtain" aria-hidden="true"><span class="curtain__mark">SOLENNE</span></div>
  <p class="sr" id="announce" role="status" aria-live="polite"></p>`;

const view = document.getElementById('view');
const header = document.getElementById('header');
const curtain = document.getElementById('curtain');
const announce = document.getElementById('announce');
const mq = { menu: document.querySelector('.menu-btn') };

/* ---------------------------------------------------------------- boot */
let booted = false;
const hideBoot = () => {
  if (booted) return; booted = true;
  bootBar.style.setProperty('--p', 1);
  setTimeout(() => boot.classList.add('is-gone'), 180);
};
let bp = 0.08;
const bootTimer = setInterval(() => { bp = Math.min(0.9, bp + (0.9 - bp) * 0.12); bootBar.style.setProperty('--p', bp); }, 140);
setTimeout(hideBoot, 9000);

/* -------------------------------------------------------------- routing */
let current = null;       // { key, page }
let pendingAnchor = null;

const parse = () => {
  const h = location.hash || '#/';
  const m = h.match(/^#\/villa\/([\w-]+)/);
  if (m) return { key: `villa:${m[1]}`, kind: 'villa', slug: m[1] };
  if (h === '#/' || h === '#') return { key: 'home', kind: 'home' };
  const id = h.slice(1);
  return { key: 'home', kind: 'home', anchor: id };
};

const scrollToId = (id, behavior = 'smooth') => {
  const t = document.getElementById(id);
  if (!t) return;
  const y = t.getBoundingClientRect().top + scrollY - (id === 'experience' ? 0 : 0);
  window.scrollTo({ top: y, behavior: reduced() ? 'auto' : behavior });
};

async function transition(swap) {
  curtain.classList.add('is-up');
  const mark = curtain.querySelector('.curtain__mark');
  if (reduced()) { await swap(); curtain.classList.remove('is-up'); return; }
  await curtain.animate([{ clipPath: 'inset(100% 0 0 0)' }, { clipPath: 'inset(0 0 0 0)' }], { duration: 800, easing: 'cubic-bezier(0.76,0,0.24,1)', fill: 'forwards' }).finished;
  mark.animate([{ opacity: 0, transform: 'translateY(14px)' }, { opacity: 1, transform: 'none' }], { duration: 500, easing: 'cubic-bezier(0.16,1,0.3,1)', fill: 'forwards' });
  await swap();
  await new Promise((r) => setTimeout(r, 380));
  await curtain.animate([{ clipPath: 'inset(0 0 0 0)' }, { clipPath: 'inset(0 0 100% 0)' }], { duration: 900, easing: 'cubic-bezier(0.76,0,0.24,1)', fill: 'forwards' }).finished;
  curtain.getAnimations().forEach((a) => a.cancel());
  curtain.classList.remove('is-up');
}

async function render(route, { first = false } = {}) {
  const swap = async () => {
    current?.page.destroy();
    view.innerHTML = '';
    let page;
    if (route.kind === 'villa') page = villaPage(route.slug);
    if (!page) page = homePage();
    page.el.tabIndex = -1;
    view.append(page.el);
    document.title = page.title || 'Solenne — Private residences on the Mediterranean';
    current = { key: page.title ? route.key : 'home', page };
    window.scrollTo(0, 0);
    document.body.dataset.page = route.kind;
    const ready = page.mount({ boot: hideBoot });
    if (route.kind !== 'home') { await ready; requestAnimationFrame(() => setTimeout(hideBoot, 250)); }
    else ready.catch((e) => { console.error(e); hideBoot(); });
    announce.textContent = document.title;
    if (!first) page.el.focus({ preventScroll: true });
    if (route.anchor || pendingAnchor) { const id = route.anchor || pendingAnchor; pendingAnchor = null; setTimeout(() => scrollToId(id, 'auto'), 120); }
  };
  if (first) await swap(); else await transition(swap);
}

async function onRoute() {
  const route = parse();
  const key = route.kind === 'villa' ? route.key : 'home';
  if (current && current.key === key) {
    if (route.anchor) scrollToId(route.anchor);
    return;
  }
  await render(route);
}
addEventListener('hashchange', onRoute);

/* In-page navigation. Works the same from the home page and from a residence. */
document.addEventListener('click', (e) => {
  const a = e.target.closest('[data-go-id]');
  if (!a) return;
  e.preventDefault();
  let id = a.dataset.goId;
  document.body.classList.remove('menu-open'); mq.menu.setAttribute('aria-expanded', 'false');
  const onVilla = document.body.dataset.page === 'villa';
  if (onVilla && id === 'private-viewing') id = 'vv-form';
  if (onVilla && !document.getElementById(id)) { pendingAnchor = id; location.hash = '#/'; return; }
  if (onVilla && a.hasAttribute('data-home')) { pendingAnchor = id; location.hash = '#/'; return; }
  scrollToId(id);
  history.replaceState(null, '', location.pathname + location.search);
});

mq.menu.addEventListener('click', () => {
  const open = !document.body.classList.contains('menu-open');
  document.body.classList.toggle('menu-open', open);
  mq.menu.setAttribute('aria-expanded', String(open));
});
addEventListener('keydown', (e) => { if (e.key === 'Escape' && document.body.classList.contains('menu-open')) mq.menu.click(); });

/* header: tucks away while reading down, returns on the way up */
let lastY = 0;
addEventListener('scroll', () => {
  const y = scrollY;
  header.classList.toggle('is-hidden', y > lastY && y > 320 && !document.body.classList.contains('menu-open'));
  lastY = y;
}, { passive: true });

/* ----------------------------------------------------------------- go */
(async () => {
  initCursor();
  await Promise.race([document.fonts?.ready, new Promise((r) => setTimeout(r, 1500))]);
  const route = parse();
  await render(route, { first: true });
  clearInterval(bootTimer);
})();
